url: http://jannypie.github.io
auto: false
server: false
lsi: false
pygments: true
permalink: /:title
# paginate: 10
exclude: ["lib", "blog.rb", "Capfile", "config", "log", "Rakefile", "tmp"]
sass:
  sass_dir: _sass
collections:
  projects:
    output: true
